import { RuleEngine, RuleEvaluationContext } from './rule-engine';
import { Strategy1_SMCLondon } from './strategies/strategy-1-smc-london';
import { Strategy2_SndEngulfing } from './strategies/strategy-2-snd-engulfing';
import { Strategy3_ScalpingSMC } from './strategies/strategy-3-scalping-smc';
import { Strategy4_NewsReversal } from './strategies/strategy-4-news-reversal';
import { BaseStrategy } from './strategies/base-strategy';
import { SignalPipeline } from './signal-pipeline';
import { logger } from '../utils/logger';
import { StrategyState } from './state-machine';

import { getSupabaseClient } from '../supabase/client';

export class TradingEngine {
  private ruleEngine: RuleEngine;
  private signalPipeline: SignalPipeline;
  private strategies: BaseStrategy[];

  constructor() {
    this.ruleEngine = new RuleEngine();
    this.signalPipeline = new SignalPipeline();
    this.strategies = [
      new Strategy1_SMCLondon(this.ruleEngine),
      new Strategy2_SndEngulfing(this.ruleEngine),
      new Strategy3_ScalpingSMC(this.ruleEngine),
      new Strategy4_NewsReversal(this.ruleEngine)
    ];
  }

  public async init() {
    logger.info('Initializing Trading Engine and loading states from persistence...');
    for (const strategy of this.strategies) {
      try {
        const lastState = await getSupabaseClient().getStrategyState(strategy.id);
        if (lastState && lastState.state_name) {
          // If the last state was terminal, we can either stay there or reset to IDLE depending on logic.
          // For now, PRD says "Restart harus memuat state terakhir yang sah."
          if (!['FINISHED', 'REJECTED', 'EXPIRED', 'SUPPRESSED'].includes(lastState.state_name)) {
            strategy.stateMachine.forceState(lastState.state_name as any, 'Loaded from persistence', lastState.signal_key, lastState.payload_json?.context);
            logger.info(`Restored state for ${strategy.id} to ${lastState.state_name}`);
          }
        }
      } catch (err: any) {
        logger.error(`Failed to load state for ${strategy.id}: ${err.message}`);
      }
    }

    // Listen to async transitions (e.g. from AI Validation)
    import('../redis/queue').then(({ getQueueManager }) => {
       getQueueManager().subscribe('events', async (msg) => {
         if (msg.payload?.type === 'STRATEGY_TRANSITION') {
            const { strategyId, state } = msg.payload;
            const strategy = this.strategies.find(s => s.id === strategyId);
            if (strategy && strategy.getCurrentState() !== state) {
               logger.info(`TradingEngine received async transition for ${strategyId} -> ${state}`);
               // Simple force state synchronization
               strategy.stateMachine.forceState(state as any, 'Async Transition Update', undefined, undefined); // Context and signalKey could be stale, but good enough for resuming flow
            }
         }
       });
    });
  }

  public processMarketData(symbol: string, timeframe: string, contextData: any) {
    logger.info(`Processing market data for ${symbol} - ${timeframe}`);
    
    const context: RuleEvaluationContext = {
      symbol,
      timeframe,
      timestamp: new Date().toISOString(),
      marketData: contextData,
      indicators: contextData.indicators || {},
      correlationId: contextData.correlationId
    };

    for (const strategy of this.strategies) {
      const prevStateName = strategy.getCurrentState();
      
      try {
        strategy.evaluate(context);
        const newStateName = strategy.getCurrentState();
        
        if (prevStateName !== newStateName) {
          logger.info(`Strategy ${strategy.name} transitioned: ${prevStateName} -> ${newStateName}`, { strategyId: strategy.id });
          
          const prevStateObject: StrategyState = { stateName: prevStateName, strategyId: strategy.id, timestamp: new Date().toISOString(), currentStatus: 'active', reason: 'previous state', nextExpectedState: null };
          
          // Retrieve the rich state generated by the transition, fallback to simple object if missing
          const newStateObject = strategy.stateMachine.lastTransitionState || { 
            stateName: newStateName, 
            strategyId: strategy.id, 
            timestamp: new Date().toISOString(), 
            currentStatus: 'active', 
            reason: 'transitioned', 
            nextExpectedState: null 
          };
          
          // Use the pipeline to process this transition
          this.signalPipeline.processStateTransition(
            strategy.id,
            prevStateObject,
            newStateObject,
            strategy.lastRuleResults,
            context
          ).catch((e: any) => {
            logger.error(`Error processing state transition for ${strategy.id}: ${e.message}`);
          });
        }
      } catch (error: any) {
        logger.error(`Error evaluating strategy ${strategy.name}: ${error.message}`, { strategyId: strategy.id });
      }
    }
  }
}
